### ISSUE TITLE
Related Software

### ISSUE THREAD

**Issue by kullrich** [maialab/grantham#3]
Hi,

just to add to the related software section:

https://www.bioconductor.org/packages/devel/bioc/vignettes/MSA2dist/inst/doc/MSA2dist.html#granthams-distance

Best regards

Kristian

**Comment by ramiromagno** [comment]
Hi Kristian,

Thank you for drawing my attention to `{MSA2dist}`.

**Comment by kullrich** [comment]
Hi Ramiro,
thanks for adding my package to the related software section.
